# Generated by Django 4.2.16 on 2025-01-06 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='title',
            new_name='movie_title',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='movies',
            new_name='movie_title',
        ),
    ]
