# Generated by Django 4.2.16 on 2025-01-06 17:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_rename_title_movie_movie_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 6, 17, 39, 49, 248669, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
