# Generated by Django 4.2.16 on 2025-01-06 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='movie_title',
            new_name='title',
        ),
    ]
