# Generated by Django 4.2.16 on 2025-01-08 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_remove_review_movie_remove_review_updated_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movie',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='created_at',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='user',
            new_name='user_id',
        ),
    ]
