# Generated by Django 4.2.16 on 2025-01-08 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_delete_movie_rename_created_at_review_created_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Username',
            new_name='name',
        ),
    ]
